import os

def write_r_embryo(factor,name,outputfile):
    script = open(outputfile,'w')
    script.write('# Options settings.\n')
    script.write('setwd("/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/%s/")\n' % factor)
    script.write('upstream=1000\n')
    script.write('downstream=1000\n')
    script.write('step=10\n')
    script.write('set_seed="False"\n')
    script.write('hmethod="mean"\n')
    script.write('zmin="None"\n')
    script.write('zmax="None"\n')
    script.write('saturation = 0.05\n')
    script.write('km=4 # kmeans number\n')
    script.write('fontsize=round(1*1.0*1920/1600, 2)\n')
    script.write('wigcount=7\n')
    script.write('siteprof=c("Embryo_%s_siteprof1","Embryo_%s_siteprof2","Embryo_%s_siteprof3","Embryo_%s_siteprof4","Embryo_%s_siteprof5","Embryo_%s_siteprof6","Embryo_%s_siteprof7")\n' % (name,name,name,name,name,name,name))
    script.write('step_num=201\n')
    script.write('xlabel=c("","","","","","","")\n')
    script.write('ylabel=c("","","","","","","")\n')
    script.write('subtitle=c("early2cell","late2cell","4cell","8cell","morula","ICM","TE")\n')
    script.write('axhline="False"\n')
    script.write('axvline="False"\n')
    script.write('\n')
    script.write('if (set_seed=="True"){\n')
    script.write('    set.seed(244913100)\n')
    script.write('}\n')
    script.write('\n')
    script.write('# ----- function for plotting a matrix ----- #\n')
    script.write('# the function is create by python\n')
    script.write('\n')
    script.write('#datafull <- read.table(siteprof[1],sep=",",header=F)\n')
    script.write('for (i in seq(wigcount)){\n')
    script.write('    data<-read.table(siteprof[i],sep=",",header=F)\n')
    script.write('    if (i==1) {\n')
    script.write('    datafull <- data\n')
    script.write('    } else {\n')
    script.write('    datafull <- cbind(datafull, data)\n')
    script.write('    }\n')
    script.write('}\n')
    script.write('ymax<-nrow(datafull)\n')
    script.write('\n')
    script.write('# decide zmin, zmax\n')
    script.write('datafull_flat <- c(as.matrix(datafull))\n')
    script.write('datafull_flat <- sort(datafull_flat)\n')
    script.write('min <- datafull_flat[1]\n')
    script.write('max <- datafull_flat[length(datafull_flat)]\n')
    script.write('\n')
    script.write('if (zmin=="None" || zmax=="None") {\n')
    script.write('    temp<-datafull_flat[round(c(saturation,0.5,1-saturation)*length(datafull_flat))]\n')
    script.write('    p20<-temp[1]\n')
    script.write('    p50<-temp[2]\n')
    script.write('    p80<-temp[3]\n')
    script.write('    zmin=p20\n')
    script.write('    zmax=p80\n')
    script.write('} else {\n')
    script.write('    zmin=max(zmin, min)\n')
    script.write('    zmax=min(zmax, max)\n')
    script.write('}\n')
    script.write('\n')
    script.write('# set color map\n')
    script.write('ColorRamp <- colorRampPalette(c("#FFFFFF","#f5c3c3","#dd2222"), bias=1)(10000)   #color list\n')
    script.write('ColorLevels <- seq(to=zmax,from=zmin, length=10000)   #number sequence\n')
    script.write('\n')
    script.write('# set png divice\n')
    script.write('pdf("Embryo_%s_heatmap.pdf",width=18,height=15)\n' % name)
    script.write('nheat=wigcount #number of heats\n')
    script.write('par(oma = c(0, 0, 3, 0))\n')
    script.write('layout(matrix(seq(nheat*2), nrow=2, ncol=nheat), widths=rep(12/nheat,nheat), heights=rep(c(0.3,1),nheat))\n')
    script.write('par(cex=fontsize)\n')
    script.write('\n')
    script.write('for (i in seq(wigcount)) {\n')
    script.write('    # draw heatmap\n')
    script.write('    data <- datafull[,seq((i-1)*step_num+1,i*step_num)]\n')
    script.write('    data[data<zmin] <- zmin\n')
    script.write('    data[data>zmax] <- zmax\n')
    script.write('    ColorRamp_ex <- ColorRamp[round( (min(data)-zmin)*10000/(zmax-zmin) ) : round( (max(data)-zmin)*10000/(zmax-zmin) )]\n')
    script.write('    par(mar=c(3.1, 2.5, 3.1, 0.8))\n')
    script.write('    plot(apply(data,2,mean),type="l",col="red",lwd=2,ylab="Normalized nucleosome tags",xlab="Distance to center",axes=F,ylim=c(0,4))\n')
    script.write('    axis(side=1,at=c(0,100,200),c("-1000","center","1000"));axis(side=2);box()\n')
    script.write('    title(main=subtitle[i],cex=2)\n')
    script.write('    image(1:ncol(data), 1:nrow(data), t(data), axes=FALSE, col=ColorRamp_ex, xlab=xlabel[i], ylab=ylabel[i], useRaster=T)\n')
    script.write('    sepxy=((downstream+upstream)/step)%/%5*step\n')
    script.write('    sepy=floor(ymax/5/10^floor(log10(ymax/5)))*10^floor(log10(ymax/5)) #the three 5 this line is var before.\n')
    script.write('    if ((upstream+downstream)/step>=5){\n')
    script.write('        axis(1,at=(seq(from=-(upstream'+'%/%'+'sepxy*sepxy),to=downstream,by=sepxy)+round(upstream/step)*step)/step+0.5,seq(from=-(upstream'+'%/%'+'sepxy*sepxy),to=downstream,by=sepxy))\n')
    script.write('    } else {\n')
    script.write('        axis(1,at=seq(6)-0.5,seq(-round(upstream/step)*step,by=step,length=6))\n')
    script.write('    }\n')
    script.write('    \n')
    script.write('    if (i==1){\n')
    script.write('        axis(2,at=seq(from=0,to=ymax,by=sepy),seq(from=0,to=ymax,by=sepy))\n')
    script.write('    }\n')
    script.write('    box()\n')
    script.write('    if (axhline=="True"){\n')
    script.write('        #draw abline\n')
    script.write('        hi = 0\n')
    script.write('        for (i in k$size){\n')
    script.write('            hi = hi+i\n')
    script.write('            abline(hi+0.5,0,lwd=5)\n')
    script.write('        }\n')
    script.write('    }\n')
    script.write('    if (axvline=="True"){\n')
    script.write('        lines(rep(round(upstream/step)+0.5,2),c(-1e10,1e10),lwd=5)\n')
    script.write('    }\n')
    script.write('}\n')
    script.write('\n')
    script.write('mtext("Embryo profile on %s motif", side = 3, line = 1, outer = TRUE, cex = 3)\n' % name)
    script.write('layout(1)\n')
    script.write('dev.off()\n')
    script.close()
    os.system('Rscript %s' %  outputfile)


def write_r_male(factor,name,outputfile):
    script = open(outputfile,'w')
    script.write('# Options settings.\n')
    script.write('setwd("/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/%s/")\n' % factor)
    script.write('upstream=1000\n')
    script.write('downstream=1000\n')
    script.write('step=10\n')
    script.write('set_seed="False"\n')
    script.write('hmethod="mean"\n')
    script.write('zmin="None"\n')
    script.write('zmax="None"\n')
    script.write('saturation = 0.05\n')
    script.write('km=4 # kmeans number\n')
    script.write('fontsize=round(1*1.0*1920/1600, 2)\n')
    script.write('wigcount=10\n')
    script.write('siteprof=c("MalePN_%s_siteprof1","MalePN_%s_siteprof2","MalePN_%s_siteprof3","MalePN_%s_siteprof4","MalePN_%s_siteprof5","MalePN_%s_siteprof6","MalePN_%s_siteprof7","MalePN_%s_siteprof8","MalePN_%s_siteprof9","MalePN_%s_siteprof10")\n' % (name,name,name,name,name,name,name,name,name,name))
    script.write('step_num=201\n')
    script.write('xlabel=c("","","","","","","")\n')
    script.write('ylabel=c("","","","","","","")\n')
    script.write('subtitle=c("Sperm","0.5h","1h","1.5h","2h","3h","4h","6h","8h","12h")\n')
    script.write('axhline="False"\n')
    script.write('axvline="False"\n')
    script.write('\n')
    script.write('if (set_seed=="True"){\n')
    script.write('    set.seed(244913100)\n')
    script.write('}\n')
    script.write('\n')
    script.write('# ----- function for plotting a matrix ----- #\n')
    script.write('# the function is create by python\n')
    script.write('\n')
    script.write('#datafull <- read.table(siteprof[1],sep=",",header=F)\n')
    script.write('for (i in seq(wigcount)){\n')
    script.write('    data<-read.table(siteprof[i],sep=",",header=F)\n')
    script.write('    if (i==1) {\n')
    script.write('    datafull <- data\n')
    script.write('    } else {\n')
    script.write('    datafull <- cbind(datafull, data)\n')
    script.write('    }\n')
    script.write('}\n')
    script.write('ymax<-nrow(datafull)\n')
    script.write('\n')
    script.write('# decide zmin, zmax\n')
    script.write('datafull_flat <- c(as.matrix(datafull))\n')
    script.write('datafull_flat <- sort(datafull_flat)\n')
    script.write('min <- datafull_flat[1]\n')
    script.write('max <- datafull_flat[length(datafull_flat)]\n')
    script.write('\n')
    script.write('if (zmin=="None" || zmax=="None") {\n')
    script.write('    temp<-datafull_flat[round(c(saturation,0.5,1-saturation)*length(datafull_flat))]\n')
    script.write('    p20<-temp[1]\n')
    script.write('    p50<-temp[2]\n')
    script.write('    p80<-temp[3]\n')
    script.write('    zmin=p20\n')
    script.write('    zmax=p80\n')
    script.write('} else {\n')
    script.write('    zmin=max(zmin, min)\n')
    script.write('    zmax=min(zmax, max)\n')
    script.write('}\n')
    script.write('\n')
    script.write('# set color map\n')
    script.write('ColorRamp <- colorRampPalette(c("#FFFFFF","#f5c3c3","#dd2222"), bias=1)(10000)   #color list\n')
    script.write('ColorLevels <- seq(to=zmax,from=zmin, length=10000)   #number sequence\n')
    script.write('\n')
    script.write('# set png divice\n')
    script.write('pdf("MalePN_%s_heatmap.pdf",width=25,height=15)\n' % name)
    script.write('nheat=wigcount #number of heats\n')
    script.write('par(oma = c(0, 0, 3, 0))\n')
    script.write('layout(matrix(seq(nheat*2), nrow=2, ncol=nheat), widths=rep(12/nheat,nheat), heights=rep(c(0.3,1),nheat))\n')
    script.write('par(cex=fontsize)\n')
    script.write('\n')
    script.write('for (i in seq(wigcount)) {\n')
    script.write('    # draw heatmap\n')
    script.write('    data <- datafull[,seq((i-1)*step_num+1,i*step_num)]\n')
    script.write('    data[data<zmin] <- zmin\n')
    script.write('    data[data>zmax] <- zmax\n')
    script.write('    ColorRamp_ex <- ColorRamp[round( (min(data)-zmin)*10000/(zmax-zmin) ) : round( (max(data)-zmin)*10000/(zmax-zmin) )]\n')
    script.write('    par(mar=c(3.1, 2.5, 3.1, 0.8))\n')
    script.write('    plot(apply(data,2,mean),type="l",col="red",lwd=2,ylab="Normalized nucleosome tags",xlab="Distance to center",axes=F,ylim=c(0,4))\n')
    script.write('    axis(side=1,at=c(0,100,200),c("-1000","center","1000"));axis(side=2);box()\n')
    script.write('    title(main=subtitle[i],cex=2)\n')
    script.write('    image(1:ncol(data), 1:nrow(data), t(data), axes=FALSE, col=ColorRamp_ex, xlab=xlabel[i], ylab=ylabel[i], useRaster=T)\n')
    script.write('    sepxy=((downstream+upstream)/step)%/%5*step\n')
    script.write('    sepy=floor(ymax/5/10^floor(log10(ymax/5)))*10^floor(log10(ymax/5)) #the three 5 this line is var before.\n')
    script.write('    if ((upstream+downstream)/step>=5){\n')
    script.write('        axis(1,at=(seq(from=-(upstream'+'%/%'+'sepxy*sepxy),to=downstream,by=sepxy)+round(upstream/step)*step)/step+0.5,seq(from=-(upstream'+'%/%'+'sepxy*sepxy),to=downstream,by=sepxy))\n')
    script.write('    } else {\n')
    script.write('        axis(1,at=seq(6)-0.5,seq(-round(upstream/step)*step,by=step,length=6))\n')
    script.write('    }\n')
    script.write('    \n')
    script.write('    if (i==1){\n')
    script.write('        axis(2,at=seq(from=0,to=ymax,by=sepy),seq(from=0,to=ymax,by=sepy))\n')
    script.write('    }\n')
    script.write('    box()\n')
    script.write('    if (axhline=="True"){\n')
    script.write('        #draw abline\n')
    script.write('        hi = 0\n')
    script.write('        for (i in k$size){\n')
    script.write('            hi = hi+i\n')
    script.write('            abline(hi+0.5,0,lwd=5)\n')
    script.write('        }\n')
    script.write('    }\n')
    script.write('    if (axvline=="True"){\n')
    script.write('        lines(rep(round(upstream/step)+0.5,2),c(-1e10,1e10),lwd=5)\n')
    script.write('    }\n')
    script.write('}\n')
    script.write('\n')
    script.write('mtext("MalePN profile on %s motif", side = 3, line = 1, outer = TRUE, cex = 3)\n' % name)
    script.write('layout(1)\n')
    script.write('dev.off()\n')
    script.close()
    os.system('Rscript %s' %  outputfile)


def write_r_female(factor,name,outputfile):
    script = open(outputfile,'w')
    script.write('# Options settings.\n')
    script.write('setwd("/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/%s/")\n' % factor)
    script.write('upstream=1000\n')
    script.write('downstream=1000\n')
    script.write('step=10\n')
    script.write('set_seed="False"\n')
    script.write('hmethod="mean"\n')
    script.write('zmin="None"\n')
    script.write('zmax="None"\n')
    script.write('saturation = 0.05\n')
    script.write('km=4 # kmeans number\n')
    script.write('fontsize=round(1*1.0*1920/1600, 2)\n')
    script.write('wigcount=10\n')
    script.write('siteprof=c("FemalePN_%s_siteprof1","FemalePN_%s_siteprof2","FemalePN_%s_siteprof3","FemalePN_%s_siteprof4","FemalePN_%s_siteprof5","FemalePN_%s_siteprof6","FemalePN_%s_siteprof7","FemalePN_%s_siteprof8","FemalePN_%s_siteprof9","FemalePN_%s_siteprof10")\n' % (name,name,name,name,name,name,name,name,name,name))
    script.write('step_num=201\n')
    script.write('xlabel=c("","","","","","","")\n')
    script.write('ylabel=c("","","","","","","")\n')
    script.write('subtitle=c("MIIOocyte","0.5h","1h","1.5h","2h","3h","4h","6h","8h","12h")\n')
    script.write('axhline="False"\n')
    script.write('axvline="False"\n')
    script.write('\n')
    script.write('if (set_seed=="True"){\n')
    script.write('    set.seed(244913100)\n')
    script.write('}\n')
    script.write('\n')
    script.write('# ----- function for plotting a matrix ----- #\n')
    script.write('# the function is create by python\n')
    script.write('\n')
    script.write('#datafull <- read.table(siteprof[1],sep=",",header=F)\n')
    script.write('for (i in seq(wigcount)){\n')
    script.write('    data<-read.table(siteprof[i],sep=",",header=F)\n')
    script.write('    if (i==1) {\n')
    script.write('    datafull <- data\n')
    script.write('    } else {\n')
    script.write('    datafull <- cbind(datafull, data)\n')
    script.write('    }\n')
    script.write('}\n')
    script.write('ymax<-nrow(datafull)\n')
    script.write('\n')
    script.write('# decide zmin, zmax\n')
    script.write('datafull_flat <- c(as.matrix(datafull))\n')
    script.write('datafull_flat <- sort(datafull_flat)\n')
    script.write('min <- datafull_flat[1]\n')
    script.write('max <- datafull_flat[length(datafull_flat)]\n')
    script.write('\n')
    script.write('if (zmin=="None" || zmax=="None") {\n')
    script.write('    temp<-datafull_flat[round(c(saturation,0.5,1-saturation)*length(datafull_flat))]\n')
    script.write('    p20<-temp[1]\n')
    script.write('    p50<-temp[2]\n')
    script.write('    p80<-temp[3]\n')
    script.write('    zmin=p20\n')
    script.write('    zmax=p80\n')
    script.write('} else {\n')
    script.write('    zmin=max(zmin, min)\n')
    script.write('    zmax=min(zmax, max)\n')
    script.write('}\n')
    script.write('\n')
    script.write('# set color map\n')
    script.write('ColorRamp <- colorRampPalette(c("#FFFFFF","#f5c3c3","#dd2222"), bias=1)(10000)   #color list\n')
    script.write('ColorLevels <- seq(to=zmax,from=zmin, length=10000)   #number sequence\n')
    script.write('\n')
    script.write('# set png divice\n')
    script.write('pdf("FemalePN_%s_heatmap.pdf",width=25,height=15)\n' % name)
    script.write('nheat=wigcount #number of heats\n')
    script.write('par(oma = c(0, 0, 3, 0))\n')
    script.write('layout(matrix(seq(nheat*2), nrow=2, ncol=nheat), widths=rep(12/nheat,nheat), heights=rep(c(0.3,1),nheat))\n')
    script.write('par(cex=fontsize)\n')
    script.write('\n')
    script.write('for (i in seq(wigcount)) {\n')
    script.write('    # draw heatmap\n')
    script.write('    data <- datafull[,seq((i-1)*step_num+1,i*step_num)]\n')
    script.write('    data[data<zmin] <- zmin\n')
    script.write('    data[data>zmax] <- zmax\n')
    script.write('    ColorRamp_ex <- ColorRamp[round( (min(data)-zmin)*10000/(zmax-zmin) ) : round( (max(data)-zmin)*10000/(zmax-zmin) )]\n')
    script.write('    par(mar=c(3.1, 2.5, 3.1, 0.8))\n')
    script.write('    plot(apply(data,2,mean),type="l",col="red",lwd=2,ylab="Normalized nucleosome tags",xlab="Distance to center",axes=F,ylim=c(0,4))\n')
    script.write('    axis(side=1,at=c(0,100,200),c("-1000","center","1000"));axis(side=2);box()\n')
    script.write('    title(main=subtitle[i],cex=2)\n')
    script.write('    image(1:ncol(data), 1:nrow(data), t(data), axes=FALSE, col=ColorRamp_ex, xlab=xlabel[i], ylab=ylabel[i], useRaster=T)\n')
    script.write('    sepxy=((downstream+upstream)/step)%/%5*step\n')
    script.write('    sepy=floor(ymax/5/10^floor(log10(ymax/5)))*10^floor(log10(ymax/5)) #the three 5 this line is var before.\n')
    script.write('    if ((upstream+downstream)/step>=5){\n')
    script.write('        axis(1,at=(seq(from=-(upstream'+'%/%'+'sepxy*sepxy),to=downstream,by=sepxy)+round(upstream/step)*step)/step+0.5,seq(from=-(upstream'+'%/%'+'sepxy*sepxy),to=downstream,by=sepxy))\n')
    script.write('    } else {\n')
    script.write('        axis(1,at=seq(6)-0.5,seq(-round(upstream/step)*step,by=step,length=6))\n')
    script.write('    }\n')
    script.write('    \n')
    script.write('    if (i==1){\n')
    script.write('        axis(2,at=seq(from=0,to=ymax,by=sepy),seq(from=0,to=ymax,by=sepy))\n')
    script.write('    }\n')
    script.write('    box()\n')
    script.write('    if (axhline=="True"){\n')
    script.write('        #draw abline\n')
    script.write('        hi = 0\n')
    script.write('        for (i in k$size){\n')
    script.write('            hi = hi+i\n')
    script.write('            abline(hi+0.5,0,lwd=5)\n')
    script.write('        }\n')
    script.write('    }\n')
    script.write('    if (axvline=="True"){\n')
    script.write('        lines(rep(round(upstream/step)+0.5,2),c(-1e10,1e10),lwd=5)\n')
    script.write('    }\n')
    script.write('}\n')
    script.write('\n')
    script.write('mtext("FemalePN profile on %s motif", side = 3, line = 1, outer = TRUE, cex = 3)\n' % name)
    script.write('layout(1)\n')
    script.write('dev.off()\n')
    script.close()
    os.system('Rscript %s' %  outputfile)

if __name__ == '__main__':
	write_r_embryo('Alx1','Alx1.MS00406','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Alx1/Embryo_Alx1.MS00406_kmeans.r')
	write_r_embryo('Alx1','Alx1.MS00407','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Alx1/Embryo_Alx1.MS00407_kmeans.r')
	write_r_embryo('Arntl','Arntl.MC00362','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Arntl/Embryo_Arntl.MC00362_kmeans.r')
	write_r_embryo('Arx','Arx.MS00409','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Arx/Embryo_Arx.MS00409_kmeans.r')
	write_r_embryo('Arx','Arx.UP00152','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Arx/Embryo_Arx.UP00152_kmeans.r')
	write_r_embryo('Atf4','Atf4.MS00295','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Atf4/Embryo_Atf4.MS00295_kmeans.r')
	write_r_embryo('Bbx','Bbx.UP00012','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Bbx/Embryo_Bbx.UP00012_kmeans.r')
	write_r_embryo('Bhlhe40','Bhlhe40.MS00252','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Bhlhe40/Embryo_Bhlhe40.MS00252_kmeans.r')
	write_r_embryo('Cbfa2t2','Cbfa2t2.MC00514','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Cbfa2t2/Embryo_Cbfa2t2.MC00514_kmeans.r')
	write_r_embryo('Cphx1','Cphx1.M01478','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Cphx1/Embryo_Cphx1.M01478_kmeans.r')
	write_r_embryo('Ctcf','Ctcf.MC00187','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Ctcf/Embryo_Ctcf.MC00187_kmeans.r')
	write_r_embryo('E2f1','E2f1.MS00815','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f1/Embryo_E2f1.MS00815_kmeans.r')
	write_r_embryo('E2f2','E2f2.MS00712','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f2/Embryo_E2f2.MS00712_kmeans.r')
	write_r_embryo('E2f4','E2f4.MC00158','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f4/Embryo_E2f4.MC00158_kmeans.r')
	write_r_embryo('E2f4','E2f4.MS00737','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f4/Embryo_E2f4.MS00737_kmeans.r')
	write_r_embryo('E2f8','E2f8.MS00739','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f8/Embryo_E2f8.MS00739_kmeans.r')
	write_r_embryo('Egr1','Egr1.MS00724','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Egr1/Embryo_Egr1.MS00724_kmeans.r')
	write_r_embryo('Elk3','Elk3.MS00023','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Elk3/Embryo_Elk3.MS00023_kmeans.r')
	write_r_embryo('Esr1','Esr1.MC00295','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Esr1/Embryo_Esr1.MC00295_kmeans.r')
	write_r_embryo('Esrrb','Esrrb.MC00512','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Esrrb/Embryo_Esrrb.MC00512_kmeans.r')
	write_r_embryo('Etv1','Etv1.UP00421','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Etv1/Embryo_Etv1.UP00421_kmeans.r')
	write_r_embryo('Etv5','Etv5.UP00412','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Etv5/Embryo_Etv5.UP00412_kmeans.r')
	write_r_embryo('Foxc1','Foxc1.MS00388','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxc1/Embryo_Foxc1.MS00388_kmeans.r')
	write_r_embryo('Foxc1','Foxc1.MS00389','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxc1/Embryo_Foxc1.MS00389_kmeans.r')
	write_r_embryo('Foxj3','Foxj3.MS00394','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/Embryo_Foxj3.MS00394_kmeans.r')
	write_r_embryo('Foxj3','Foxj3.MS00395','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/Embryo_Foxj3.MS00395_kmeans.r')
	write_r_embryo('Foxj3','Foxj3.MS00396','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/Embryo_Foxj3.MS00396_kmeans.r')
	write_r_embryo('Foxj3','Foxj3.MS00397','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/Embryo_Foxj3.MS00397_kmeans.r')
	write_r_embryo('Foxk1','Foxk1.MS00398','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxk1/Embryo_Foxk1.MS00398_kmeans.r')
	write_r_embryo('Foxk1','Foxk1.MS00399','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxk1/Embryo_Foxk1.MS00399_kmeans.r')
	write_r_embryo('Gata3','Gata3.MC00326','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gata3/Embryo_Gata3.MC00326_kmeans.r')
	write_r_embryo('Gata4','Gata4.MC00324','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gata4/Embryo_Gata4.MC00324_kmeans.r')
	write_r_embryo('Gbx2','Gbx2.MS00469','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gbx2/Embryo_Gbx2.MS00469_kmeans.r')
	write_r_embryo('Gmeb1','Gmeb1.UP00084','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gmeb1/Embryo_Gmeb1.UP00084_kmeans.r')
	write_r_embryo('Hmbox1','Hmbox1.UP00161','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Hmbox1/Embryo_Hmbox1.UP00161_kmeans.r')
	write_r_embryo('Hsf1','Hsf1.MC00368','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Hsf1/Embryo_Hsf1.MC00368_kmeans.r')
	write_r_embryo('Isl2','Isl2.UP00170','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Isl2/Embryo_Isl2.UP00170_kmeans.r')
	write_r_embryo('Klf4','Klf4.MC00109','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Klf4/Embryo_Klf4.MC00109_kmeans.r')
	write_r_embryo('Klf7','Klf7.UP00093','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Klf7/Embryo_Klf7.UP00093_kmeans.r')
	write_r_embryo('Lbx2','Lbx2.UP00120','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lbx2/Embryo_Lbx2.UP00120_kmeans.r')
	write_r_embryo('Lhx8','Lhx8.MS00548','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/Embryo_Lhx8.MS00548_kmeans.r')
	write_r_embryo('Lhx8','Lhx8.MS00549','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/Embryo_Lhx8.MS00549_kmeans.r')
	write_r_embryo('Lhx8','Lhx8.MS00550','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/Embryo_Lhx8.MS00550_kmeans.r')
	write_r_embryo('Lhx8','Lhx8.UP00184','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/Embryo_Lhx8.UP00184_kmeans.r')
	write_r_embryo('Mafk','Mafk.UP00044','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Mafk/Embryo_Mafk.UP00044_kmeans.r')
	write_r_embryo('Max','Max.MC00461','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Max/Embryo_Max.MC00461_kmeans.r')
	write_r_embryo('Meis2','Meis2.MS00086','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Meis2/Embryo_Meis2.MS00086_kmeans.r')
	write_r_embryo('Meis2','Meis2.MS00087','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Meis2/Embryo_Meis2.MS00087_kmeans.r')
	write_r_embryo('Mlx','Mlx.MS00270','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Mlx/Embryo_Mlx.MS00270_kmeans.r')
	write_r_embryo('Mybl1','Mybl1.UP00081','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Mybl1/Embryo_Mybl1.UP00081_kmeans.r')
	write_r_embryo('Nfya','Nfya.MC00191','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nfya/Embryo_Nfya.MC00191_kmeans.r')
	write_r_embryo('Nobox','Nobox.MA0125','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nobox/Embryo_Nobox.MA0125_kmeans.r')
	write_r_embryo('Nr1d2','Nr1d2.MC00186','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr1d2/Embryo_Nr1d2.MC00186_kmeans.r')
	write_r_embryo('Nr1h2','Nr1h2.MC00448','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr1h2/Embryo_Nr1h2.MC00448_kmeans.r')
	write_r_embryo('Nr2e1','Nr2e1.MS00666','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr2e1/Embryo_Nr2e1.MS00666_kmeans.r')
	write_r_embryo('Nr2e1','Nr2e1.MS00668','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr2e1/Embryo_Nr2e1.MS00668_kmeans.r')
	write_r_embryo('Nr3c1','Nr3c1.MC00396','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr3c1/Embryo_Nr3c1.MC00396_kmeans.r')
	write_r_embryo('Nr5a2','Nr5a2.MC00352','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr5a2/Embryo_Nr5a2.MC00352_kmeans.r')
	write_r_embryo('Obox1','Obox1.M01450','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox1/Embryo_Obox1.M01450_kmeans.r')
	write_r_embryo('Obox2','Obox2.M01364','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox2/Embryo_Obox2.M01364_kmeans.r')
	write_r_embryo('Obox3','Obox3.M01466','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox3/Embryo_Obox3.M01466_kmeans.r')
	write_r_embryo('Obox5','Obox5.M01480','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox5/Embryo_Obox5.M01480_kmeans.r')
	write_r_embryo('Osr2','Osr2.UP00052','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Osr2/Embryo_Osr2.UP00052_kmeans.r')
	write_r_embryo('Otx1','Otx1.MS00586','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Otx1/Embryo_Otx1.MS00586_kmeans.r')
	write_r_embryo('Otx1','Otx1.MS00587','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Otx1/Embryo_Otx1.MS00587_kmeans.r')
	write_r_embryo('Pdx1','Pdx1.MC00165','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pdx1/Embryo_Pdx1.MC00165_kmeans.r')
	write_r_embryo('Pknox2','Pknox2.MS00093','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pknox2/Embryo_Pknox2.MS00093_kmeans.r')
	write_r_embryo('Pou2f2','Pou2f2.MS00158','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pou2f2/Embryo_Pou2f2.MS00158_kmeans.r')
	write_r_embryo('Pou2f2','Pou2f2.MS00159','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pou2f2/Embryo_Pou2f2.MS00159_kmeans.r')
	write_r_embryo('Pou5f1','Pou5f1.MC00233','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pou5f1/Embryo_Pou5f1.MC00233_kmeans.r')
	write_r_embryo('Ppara','Ppara.MC00134','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Ppara/Embryo_Ppara.MC00134_kmeans.r')
	write_r_embryo('Pparg','Pparg.MC00130','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pparg/Embryo_Pparg.MC00130_kmeans.r')
	write_r_embryo('Rara','Rara.MC00252','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/Embryo_Rara.MC00252_kmeans.r')
	write_r_embryo('Rara','Rara.MS00696','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/Embryo_Rara.MS00696_kmeans.r')
	write_r_embryo('Rara','Rara.MS00697','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/Embryo_Rara.MS00697_kmeans.r')
	write_r_embryo('Rara','Rara.MS00698','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/Embryo_Rara.MS00698_kmeans.r')
	write_r_embryo('Rarb','Rarb.MS00699','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rarb/Embryo_Rarb.MS00699_kmeans.r')
	write_r_embryo('Rarb','Rarb.MS00700','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rarb/Embryo_Rarb.MS00700_kmeans.r')
	write_r_embryo('Rarb','Rarb.MS00702','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rarb/Embryo_Rarb.MS00702_kmeans.r')
	write_r_embryo('Rbfox2','Rbfox2.MC00416','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rbfox2/Embryo_Rbfox2.MC00416_kmeans.r')
	write_r_embryo('Rela','Rela.MC00135','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rela/Embryo_Rela.MC00135_kmeans.r')
	write_r_embryo('Rest','Rest.MC00125','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rest/Embryo_Rest.MC00125_kmeans.r')
	write_r_embryo('Rfx1','Rfx1.MC00144','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rfx1/Embryo_Rfx1.MC00144_kmeans.r')
	write_r_embryo('Rfx2','Rfx2.MS00170','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rfx2/Embryo_Rfx2.MS00170_kmeans.r')
	write_r_embryo('Rfx2','Rfx2.MS00171','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rfx2/Embryo_Rfx2.MS00171_kmeans.r')
	write_r_embryo('Rxra','Rxra.MC00471','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rxra/Embryo_Rxra.MC00471_kmeans.r')
	write_r_embryo('Rxra','Rxra.MS00706','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rxra/Embryo_Rxra.MS00706_kmeans.r')
	write_r_embryo('Rxra','Rxra.MS00707','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rxra/Embryo_Rxra.MS00707_kmeans.r')
	write_r_embryo('Shox2','Shox2.MS00615','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Shox2/Embryo_Shox2.MS00615_kmeans.r')
	write_r_embryo('Smad2','Smad2.MC00146','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Smad2/Embryo_Smad2.MC00146_kmeans.r')
	write_r_embryo('Snai1','Snai1.MC00183','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Snai1/Embryo_Snai1.MC00183_kmeans.r')
	write_r_embryo('Sox15','Sox15.UP00075','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox15/Embryo_Sox15.UP00075_kmeans.r')
	write_r_embryo('Sox2','Sox2.MC00303','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox2/Embryo_Sox2.MC00303_kmeans.r')
	write_r_embryo('Sox6','Sox6.MC00305','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox6/Embryo_Sox6.MC00305_kmeans.r')
	write_r_embryo('Sox8','Sox8.UP00051','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox8/Embryo_Sox8.UP00051_kmeans.r')
	write_r_embryo('Srebf1','Srebf1.MS00282','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Srebf1/Embryo_Srebf1.MS00282_kmeans.r')
	write_r_embryo('Srf','Srf.MC00329','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Srf/Embryo_Srf.MC00329_kmeans.r')
	write_r_embryo('Stat3','Stat3.MC00140','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Stat3/Embryo_Stat3.MC00140_kmeans.r')
	write_r_embryo('Stat5a','Stat5a.MC00205','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Stat5a/Embryo_Stat5a.MC00205_kmeans.r')
	write_r_embryo('Tbx3','Tbx3.MC00221','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tbx3/Embryo_Tbx3.MC00221_kmeans.r')
	write_r_embryo('Tcf3','Tcf3.MC00265','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tcf3/Embryo_Tcf3.MC00265_kmeans.r')
	write_r_embryo('Tcf7','Tcf7.MS00054','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tcf7/Embryo_Tcf7.MS00054_kmeans.r')
	write_r_embryo('Tfap2b','Tfap2b.UP00010','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfap2b/Embryo_Tfap2b.UP00010_kmeans.r')
	write_r_embryo('Tfap2c','Tfap2c.UP00087','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfap2c/Embryo_Tfap2c.UP00087_kmeans.r')
	write_r_embryo('Tfap2e','Tfap2e.UP00028','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfap2e/Embryo_Tfap2e.UP00028_kmeans.r')
	write_r_embryo('Tfcp2l1','Tfcp2l1.MA0145','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfcp2l1/Embryo_Tfcp2l1.MA0145_kmeans.r')
	write_r_embryo('Trp53','Trp53.MS00717','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/Embryo_Trp53.MS00717_kmeans.r')
	write_r_embryo('Trp53','Trp53.MS00718','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/Embryo_Trp53.MS00718_kmeans.r')
	write_r_embryo('Trp53','Trp53.MS00719','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/Embryo_Trp53.MS00719_kmeans.r')
	write_r_embryo('Trp73','Trp73.MS00720','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp73/Embryo_Trp73.MS00720_kmeans.r')
	write_r_embryo('Trp53','Trp53.M01655','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/Embryo_Trp53.M01655_kmeans.r')
	write_r_embryo('Trp53','Trp53.MC00377','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/Embryo_Trp53.MC00377_kmeans.r')
	write_r_embryo('Trp63','Trp63.M01656','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp63/Embryo_Trp63.M01656_kmeans.r')
	write_r_embryo('Usf2','Usf2.MC00169','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Usf2/Embryo_Usf2.MC00169_kmeans.r')
	write_r_embryo('Yy2','Yy2.M01694','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Yy2/Embryo_Yy2.M01694_kmeans.r')
	write_r_embryo('Zbtb14','Zbtb14.UP00065','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zbtb14/Embryo_Zbtb14.UP00065_kmeans.r')
	write_r_embryo('Zfp281','Zfp281.UP00021','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp281/Embryo_Zfp281.UP00021_kmeans.r')
	write_r_embryo('Zfp410','Zfp410.UP00033','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp410/Embryo_Zfp410.UP00033_kmeans.r')
	write_r_embryo('Zfp423','Zfp423.MA0116','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp423/Embryo_Zfp423.MA0116_kmeans.r')
	write_r_embryo('Zfp652','Zfp652.MS00501','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp652/Embryo_Zfp652.MS00501_kmeans.r')
	write_r_embryo('Zfp691','Zfp691.UP00095','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp691/Embryo_Zfp691.UP00095_kmeans.r')
	write_r_embryo('Zscan10','Zscan10.M01742','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zscan10/Embryo_Zscan10.M01742_kmeans.r')
	write_r_male('Alx1','Alx1.MS00406','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Alx1/MalePN_Alx1.MS00406_kmeans.r')
	write_r_male('Alx1','Alx1.MS00407','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Alx1/MalePN_Alx1.MS00407_kmeans.r')
	write_r_male('Arntl','Arntl.MC00362','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Arntl/MalePN_Arntl.MC00362_kmeans.r')
	write_r_male('Arx','Arx.MS00409','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Arx/MalePN_Arx.MS00409_kmeans.r')
	write_r_male('Arx','Arx.UP00152','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Arx/MalePN_Arx.UP00152_kmeans.r')
	write_r_male('Atf4','Atf4.MS00295','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Atf4/MalePN_Atf4.MS00295_kmeans.r')
	write_r_male('Bbx','Bbx.UP00012','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Bbx/MalePN_Bbx.UP00012_kmeans.r')
	write_r_male('Bhlhe40','Bhlhe40.MS00252','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Bhlhe40/MalePN_Bhlhe40.MS00252_kmeans.r')
	write_r_male('Cbfa2t2','Cbfa2t2.MC00514','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Cbfa2t2/MalePN_Cbfa2t2.MC00514_kmeans.r')
	write_r_male('Cphx1','Cphx1.M01478','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Cphx1/MalePN_Cphx1.M01478_kmeans.r')
	write_r_male('Ctcf','Ctcf.MC00187','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Ctcf/MalePN_Ctcf.MC00187_kmeans.r')
	write_r_male('E2f1','E2f1.MS00815','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f1/MalePN_E2f1.MS00815_kmeans.r')
	write_r_male('E2f2','E2f2.MS00712','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f2/MalePN_E2f2.MS00712_kmeans.r')
	write_r_male('E2f4','E2f4.MC00158','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f4/MalePN_E2f4.MC00158_kmeans.r')
	write_r_male('E2f4','E2f4.MS00737','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f4/MalePN_E2f4.MS00737_kmeans.r')
	write_r_male('E2f8','E2f8.MS00739','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f8/MalePN_E2f8.MS00739_kmeans.r')
	write_r_male('Egr1','Egr1.MS00724','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Egr1/MalePN_Egr1.MS00724_kmeans.r')
	write_r_male('Elk3','Elk3.MS00023','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Elk3/MalePN_Elk3.MS00023_kmeans.r')
	write_r_male('Esr1','Esr1.MC00295','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Esr1/MalePN_Esr1.MC00295_kmeans.r')
	write_r_male('Esrrb','Esrrb.MC00512','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Esrrb/MalePN_Esrrb.MC00512_kmeans.r')
	write_r_male('Etv1','Etv1.UP00421','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Etv1/MalePN_Etv1.UP00421_kmeans.r')
	write_r_male('Etv5','Etv5.UP00412','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Etv5/MalePN_Etv5.UP00412_kmeans.r')
	write_r_male('Foxc1','Foxc1.MS00388','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxc1/MalePN_Foxc1.MS00388_kmeans.r')
	write_r_male('Foxc1','Foxc1.MS00389','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxc1/MalePN_Foxc1.MS00389_kmeans.r')
	write_r_male('Foxj3','Foxj3.MS00394','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/MalePN_Foxj3.MS00394_kmeans.r')
	write_r_male('Foxj3','Foxj3.MS00395','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/MalePN_Foxj3.MS00395_kmeans.r')
	write_r_male('Foxj3','Foxj3.MS00396','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/MalePN_Foxj3.MS00396_kmeans.r')
	write_r_male('Foxj3','Foxj3.MS00397','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/MalePN_Foxj3.MS00397_kmeans.r')
	write_r_male('Foxk1','Foxk1.MS00398','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxk1/MalePN_Foxk1.MS00398_kmeans.r')
	write_r_male('Foxk1','Foxk1.MS00399','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxk1/MalePN_Foxk1.MS00399_kmeans.r')
	write_r_male('Gata3','Gata3.MC00326','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gata3/MalePN_Gata3.MC00326_kmeans.r')
	write_r_male('Gata4','Gata4.MC00324','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gata4/MalePN_Gata4.MC00324_kmeans.r')
	write_r_male('Gbx2','Gbx2.MS00469','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gbx2/MalePN_Gbx2.MS00469_kmeans.r')
	write_r_male('Gmeb1','Gmeb1.UP00084','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gmeb1/MalePN_Gmeb1.UP00084_kmeans.r')
	write_r_male('Hmbox1','Hmbox1.UP00161','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Hmbox1/MalePN_Hmbox1.UP00161_kmeans.r')
	write_r_male('Hsf1','Hsf1.MC00368','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Hsf1/MalePN_Hsf1.MC00368_kmeans.r')
	write_r_male('Isl2','Isl2.UP00170','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Isl2/MalePN_Isl2.UP00170_kmeans.r')
	write_r_male('Klf4','Klf4.MC00109','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Klf4/MalePN_Klf4.MC00109_kmeans.r')
	write_r_male('Klf7','Klf7.UP00093','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Klf7/MalePN_Klf7.UP00093_kmeans.r')
	write_r_male('Lbx2','Lbx2.UP00120','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lbx2/MalePN_Lbx2.UP00120_kmeans.r')
	write_r_male('Lhx8','Lhx8.MS00548','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/MalePN_Lhx8.MS00548_kmeans.r')
	write_r_male('Lhx8','Lhx8.MS00549','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/MalePN_Lhx8.MS00549_kmeans.r')
	write_r_male('Lhx8','Lhx8.MS00550','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/MalePN_Lhx8.MS00550_kmeans.r')
	write_r_male('Lhx8','Lhx8.UP00184','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/MalePN_Lhx8.UP00184_kmeans.r')
	write_r_male('Mafk','Mafk.UP00044','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Mafk/MalePN_Mafk.UP00044_kmeans.r')
	write_r_male('Max','Max.MC00461','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Max/MalePN_Max.MC00461_kmeans.r')
	write_r_male('Meis2','Meis2.MS00086','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Meis2/MalePN_Meis2.MS00086_kmeans.r')
	write_r_male('Meis2','Meis2.MS00087','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Meis2/MalePN_Meis2.MS00087_kmeans.r')
	write_r_male('Mlx','Mlx.MS00270','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Mlx/MalePN_Mlx.MS00270_kmeans.r')
	write_r_male('Mybl1','Mybl1.UP00081','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Mybl1/MalePN_Mybl1.UP00081_kmeans.r')
	write_r_male('Nfya','Nfya.MC00191','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nfya/MalePN_Nfya.MC00191_kmeans.r')
	write_r_male('Nobox','Nobox.MA0125','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nobox/MalePN_Nobox.MA0125_kmeans.r')
	write_r_male('Nr1d2','Nr1d2.MC00186','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr1d2/MalePN_Nr1d2.MC00186_kmeans.r')
	write_r_male('Nr1h2','Nr1h2.MC00448','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr1h2/MalePN_Nr1h2.MC00448_kmeans.r')
	write_r_male('Nr2e1','Nr2e1.MS00666','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr2e1/MalePN_Nr2e1.MS00666_kmeans.r')
	write_r_male('Nr2e1','Nr2e1.MS00668','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr2e1/MalePN_Nr2e1.MS00668_kmeans.r')
	write_r_male('Nr3c1','Nr3c1.MC00396','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr3c1/MalePN_Nr3c1.MC00396_kmeans.r')
	write_r_male('Nr5a2','Nr5a2.MC00352','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr5a2/MalePN_Nr5a2.MC00352_kmeans.r')
	write_r_male('Obox1','Obox1.M01450','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox1/MalePN_Obox1.M01450_kmeans.r')
	write_r_male('Obox2','Obox2.M01364','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox2/MalePN_Obox2.M01364_kmeans.r')
	write_r_male('Obox3','Obox3.M01466','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox3/MalePN_Obox3.M01466_kmeans.r')
	write_r_male('Obox5','Obox5.M01480','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox5/MalePN_Obox5.M01480_kmeans.r')
	write_r_male('Osr2','Osr2.UP00052','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Osr2/MalePN_Osr2.UP00052_kmeans.r')
	write_r_male('Otx1','Otx1.MS00586','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Otx1/MalePN_Otx1.MS00586_kmeans.r')
	write_r_male('Otx1','Otx1.MS00587','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Otx1/MalePN_Otx1.MS00587_kmeans.r')
	write_r_male('Pdx1','Pdx1.MC00165','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pdx1/MalePN_Pdx1.MC00165_kmeans.r')
	write_r_male('Pknox2','Pknox2.MS00093','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pknox2/MalePN_Pknox2.MS00093_kmeans.r')
	write_r_male('Pou2f2','Pou2f2.MS00158','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pou2f2/MalePN_Pou2f2.MS00158_kmeans.r')
	write_r_male('Pou2f2','Pou2f2.MS00159','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pou2f2/MalePN_Pou2f2.MS00159_kmeans.r')
	write_r_male('Pou5f1','Pou5f1.MC00233','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pou5f1/MalePN_Pou5f1.MC00233_kmeans.r')
	write_r_male('Ppara','Ppara.MC00134','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Ppara/MalePN_Ppara.MC00134_kmeans.r')
	write_r_male('Pparg','Pparg.MC00130','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pparg/MalePN_Pparg.MC00130_kmeans.r')
	write_r_male('Rara','Rara.MC00252','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/MalePN_Rara.MC00252_kmeans.r')
	write_r_male('Rara','Rara.MS00696','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/MalePN_Rara.MS00696_kmeans.r')
	write_r_male('Rara','Rara.MS00697','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/MalePN_Rara.MS00697_kmeans.r')
	write_r_male('Rara','Rara.MS00698','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/MalePN_Rara.MS00698_kmeans.r')
	write_r_male('Rarb','Rarb.MS00699','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rarb/MalePN_Rarb.MS00699_kmeans.r')
	write_r_male('Rarb','Rarb.MS00700','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rarb/MalePN_Rarb.MS00700_kmeans.r')
	write_r_male('Rarb','Rarb.MS00702','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rarb/MalePN_Rarb.MS00702_kmeans.r')
	write_r_male('Rbfox2','Rbfox2.MC00416','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rbfox2/MalePN_Rbfox2.MC00416_kmeans.r')
	write_r_male('Rela','Rela.MC00135','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rela/MalePN_Rela.MC00135_kmeans.r')
	write_r_male('Rest','Rest.MC00125','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rest/MalePN_Rest.MC00125_kmeans.r')
	write_r_male('Rfx1','Rfx1.MC00144','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rfx1/MalePN_Rfx1.MC00144_kmeans.r')
	write_r_male('Rfx2','Rfx2.MS00170','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rfx2/MalePN_Rfx2.MS00170_kmeans.r')
	write_r_male('Rfx2','Rfx2.MS00171','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rfx2/MalePN_Rfx2.MS00171_kmeans.r')
	write_r_male('Rxra','Rxra.MC00471','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rxra/MalePN_Rxra.MC00471_kmeans.r')
	write_r_male('Rxra','Rxra.MS00706','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rxra/MalePN_Rxra.MS00706_kmeans.r')
	write_r_male('Rxra','Rxra.MS00707','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rxra/MalePN_Rxra.MS00707_kmeans.r')
	write_r_male('Shox2','Shox2.MS00615','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Shox2/MalePN_Shox2.MS00615_kmeans.r')
	write_r_male('Smad2','Smad2.MC00146','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Smad2/MalePN_Smad2.MC00146_kmeans.r')
	write_r_male('Snai1','Snai1.MC00183','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Snai1/MalePN_Snai1.MC00183_kmeans.r')
	write_r_male('Sox15','Sox15.UP00075','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox15/MalePN_Sox15.UP00075_kmeans.r')
	write_r_male('Sox2','Sox2.MC00303','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox2/MalePN_Sox2.MC00303_kmeans.r')
	write_r_male('Sox6','Sox6.MC00305','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox6/MalePN_Sox6.MC00305_kmeans.r')
	write_r_male('Sox8','Sox8.UP00051','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox8/MalePN_Sox8.UP00051_kmeans.r')
	write_r_male('Srebf1','Srebf1.MS00282','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Srebf1/MalePN_Srebf1.MS00282_kmeans.r')
	write_r_male('Srf','Srf.MC00329','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Srf/MalePN_Srf.MC00329_kmeans.r')
	write_r_male('Stat3','Stat3.MC00140','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Stat3/MalePN_Stat3.MC00140_kmeans.r')
	write_r_male('Stat5a','Stat5a.MC00205','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Stat5a/MalePN_Stat5a.MC00205_kmeans.r')
	write_r_male('Tbx3','Tbx3.MC00221','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tbx3/MalePN_Tbx3.MC00221_kmeans.r')
	write_r_male('Tcf3','Tcf3.MC00265','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tcf3/MalePN_Tcf3.MC00265_kmeans.r')
	write_r_male('Tcf7','Tcf7.MS00054','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tcf7/MalePN_Tcf7.MS00054_kmeans.r')
	write_r_male('Tfap2b','Tfap2b.UP00010','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfap2b/MalePN_Tfap2b.UP00010_kmeans.r')
	write_r_male('Tfap2c','Tfap2c.UP00087','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfap2c/MalePN_Tfap2c.UP00087_kmeans.r')
	write_r_male('Tfap2e','Tfap2e.UP00028','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfap2e/MalePN_Tfap2e.UP00028_kmeans.r')
	write_r_male('Tfcp2l1','Tfcp2l1.MA0145','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfcp2l1/MalePN_Tfcp2l1.MA0145_kmeans.r')
	write_r_male('Trp53','Trp53.MS00717','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/MalePN_Trp53.MS00717_kmeans.r')
	write_r_male('Trp53','Trp53.MS00718','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/MalePN_Trp53.MS00718_kmeans.r')
	write_r_male('Trp53','Trp53.MS00719','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/MalePN_Trp53.MS00719_kmeans.r')
	write_r_male('Trp73','Trp73.MS00720','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp73/MalePN_Trp73.MS00720_kmeans.r')
	write_r_male('Trp53','Trp53.M01655','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/MalePN_Trp53.M01655_kmeans.r')
	write_r_male('Trp53','Trp53.MC00377','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/MalePN_Trp53.MC00377_kmeans.r')
	write_r_male('Trp63','Trp63.M01656','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp63/MalePN_Trp63.M01656_kmeans.r')
	write_r_male('Usf2','Usf2.MC00169','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Usf2/MalePN_Usf2.MC00169_kmeans.r')
	write_r_male('Yy2','Yy2.M01694','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Yy2/MalePN_Yy2.M01694_kmeans.r')
	write_r_male('Zbtb14','Zbtb14.UP00065','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zbtb14/MalePN_Zbtb14.UP00065_kmeans.r')
	write_r_male('Zfp281','Zfp281.UP00021','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp281/MalePN_Zfp281.UP00021_kmeans.r')
	write_r_male('Zfp410','Zfp410.UP00033','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp410/MalePN_Zfp410.UP00033_kmeans.r')
	write_r_male('Zfp423','Zfp423.MA0116','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp423/MalePN_Zfp423.MA0116_kmeans.r')
	write_r_male('Zfp652','Zfp652.MS00501','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp652/MalePN_Zfp652.MS00501_kmeans.r')
	write_r_male('Zfp691','Zfp691.UP00095','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp691/MalePN_Zfp691.UP00095_kmeans.r')
	write_r_male('Zscan10','Zscan10.M01742','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zscan10/MalePN_Zscan10.M01742_kmeans.r')
	write_r_female('Alx1','Alx1.MS00406','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Alx1/FemalePN_Alx1.MS00406_kmeans.r')
	write_r_female('Alx1','Alx1.MS00407','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Alx1/FemalePN_Alx1.MS00407_kmeans.r')
	write_r_female('Arntl','Arntl.MC00362','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Arntl/FemalePN_Arntl.MC00362_kmeans.r')
	write_r_female('Arx','Arx.MS00409','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Arx/FemalePN_Arx.MS00409_kmeans.r')
	write_r_female('Arx','Arx.UP00152','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Arx/FemalePN_Arx.UP00152_kmeans.r')
	write_r_female('Atf4','Atf4.MS00295','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Atf4/FemalePN_Atf4.MS00295_kmeans.r')
	write_r_female('Bbx','Bbx.UP00012','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Bbx/FemalePN_Bbx.UP00012_kmeans.r')
	write_r_female('Bhlhe40','Bhlhe40.MS00252','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Bhlhe40/FemalePN_Bhlhe40.MS00252_kmeans.r')
	write_r_female('Cbfa2t2','Cbfa2t2.MC00514','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Cbfa2t2/FemalePN_Cbfa2t2.MC00514_kmeans.r')
	write_r_female('Cphx1','Cphx1.M01478','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Cphx1/FemalePN_Cphx1.M01478_kmeans.r')
	write_r_female('Ctcf','Ctcf.MC00187','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Ctcf/FemalePN_Ctcf.MC00187_kmeans.r')
	write_r_female('E2f1','E2f1.MS00815','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f1/FemalePN_E2f1.MS00815_kmeans.r')
	write_r_female('E2f2','E2f2.MS00712','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f2/FemalePN_E2f2.MS00712_kmeans.r')
	write_r_female('E2f4','E2f4.MC00158','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f4/FemalePN_E2f4.MC00158_kmeans.r')
	write_r_female('E2f4','E2f4.MS00737','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f4/FemalePN_E2f4.MS00737_kmeans.r')
	write_r_female('E2f8','E2f8.MS00739','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/E2f8/FemalePN_E2f8.MS00739_kmeans.r')
	write_r_female('Egr1','Egr1.MS00724','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Egr1/FemalePN_Egr1.MS00724_kmeans.r')
	write_r_female('Elk3','Elk3.MS00023','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Elk3/FemalePN_Elk3.MS00023_kmeans.r')
	write_r_female('Esr1','Esr1.MC00295','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Esr1/FemalePN_Esr1.MC00295_kmeans.r')
	write_r_female('Esrrb','Esrrb.MC00512','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Esrrb/FemalePN_Esrrb.MC00512_kmeans.r')
	write_r_female('Etv1','Etv1.UP00421','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Etv1/FemalePN_Etv1.UP00421_kmeans.r')
	write_r_female('Etv5','Etv5.UP00412','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Etv5/FemalePN_Etv5.UP00412_kmeans.r')
	write_r_female('Foxc1','Foxc1.MS00388','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxc1/FemalePN_Foxc1.MS00388_kmeans.r')
	write_r_female('Foxc1','Foxc1.MS00389','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxc1/FemalePN_Foxc1.MS00389_kmeans.r')
	write_r_female('Foxj3','Foxj3.MS00394','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/FemalePN_Foxj3.MS00394_kmeans.r')
	write_r_female('Foxj3','Foxj3.MS00395','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/FemalePN_Foxj3.MS00395_kmeans.r')
	write_r_female('Foxj3','Foxj3.MS00396','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/FemalePN_Foxj3.MS00396_kmeans.r')
	write_r_female('Foxj3','Foxj3.MS00397','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxj3/FemalePN_Foxj3.MS00397_kmeans.r')
	write_r_female('Foxk1','Foxk1.MS00398','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxk1/FemalePN_Foxk1.MS00398_kmeans.r')
	write_r_female('Foxk1','Foxk1.MS00399','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Foxk1/FemalePN_Foxk1.MS00399_kmeans.r')
	write_r_female('Gata3','Gata3.MC00326','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gata3/FemalePN_Gata3.MC00326_kmeans.r')
	write_r_female('Gata4','Gata4.MC00324','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gata4/FemalePN_Gata4.MC00324_kmeans.r')
	write_r_female('Gbx2','Gbx2.MS00469','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gbx2/FemalePN_Gbx2.MS00469_kmeans.r')
	write_r_female('Gmeb1','Gmeb1.UP00084','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Gmeb1/FemalePN_Gmeb1.UP00084_kmeans.r')
	write_r_female('Hmbox1','Hmbox1.UP00161','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Hmbox1/FemalePN_Hmbox1.UP00161_kmeans.r')
	write_r_female('Hsf1','Hsf1.MC00368','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Hsf1/FemalePN_Hsf1.MC00368_kmeans.r')
	write_r_female('Isl2','Isl2.UP00170','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Isl2/FemalePN_Isl2.UP00170_kmeans.r')
	write_r_female('Klf4','Klf4.MC00109','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Klf4/FemalePN_Klf4.MC00109_kmeans.r')
	write_r_female('Klf7','Klf7.UP00093','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Klf7/FemalePN_Klf7.UP00093_kmeans.r')
	write_r_female('Lbx2','Lbx2.UP00120','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lbx2/FemalePN_Lbx2.UP00120_kmeans.r')
	write_r_female('Lhx8','Lhx8.MS00548','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/FemalePN_Lhx8.MS00548_kmeans.r')
	write_r_female('Lhx8','Lhx8.MS00549','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/FemalePN_Lhx8.MS00549_kmeans.r')
	write_r_female('Lhx8','Lhx8.MS00550','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/FemalePN_Lhx8.MS00550_kmeans.r')
	write_r_female('Lhx8','Lhx8.UP00184','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Lhx8/FemalePN_Lhx8.UP00184_kmeans.r')
	write_r_female('Mafk','Mafk.UP00044','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Mafk/FemalePN_Mafk.UP00044_kmeans.r')
	write_r_female('Max','Max.MC00461','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Max/FemalePN_Max.MC00461_kmeans.r')
	write_r_female('Meis2','Meis2.MS00086','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Meis2/FemalePN_Meis2.MS00086_kmeans.r')
	write_r_female('Meis2','Meis2.MS00087','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Meis2/FemalePN_Meis2.MS00087_kmeans.r')
	write_r_female('Mlx','Mlx.MS00270','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Mlx/FemalePN_Mlx.MS00270_kmeans.r')
	write_r_female('Mybl1','Mybl1.UP00081','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Mybl1/FemalePN_Mybl1.UP00081_kmeans.r')
	write_r_female('Nfya','Nfya.MC00191','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nfya/FemalePN_Nfya.MC00191_kmeans.r')
	write_r_female('Nobox','Nobox.MA0125','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nobox/FemalePN_Nobox.MA0125_kmeans.r')
	write_r_female('Nr1d2','Nr1d2.MC00186','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr1d2/FemalePN_Nr1d2.MC00186_kmeans.r')
	write_r_female('Nr1h2','Nr1h2.MC00448','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr1h2/FemalePN_Nr1h2.MC00448_kmeans.r')
	write_r_female('Nr2e1','Nr2e1.MS00666','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr2e1/FemalePN_Nr2e1.MS00666_kmeans.r')
	write_r_female('Nr2e1','Nr2e1.MS00668','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr2e1/FemalePN_Nr2e1.MS00668_kmeans.r')
	write_r_female('Nr3c1','Nr3c1.MC00396','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr3c1/FemalePN_Nr3c1.MC00396_kmeans.r')
	write_r_female('Nr5a2','Nr5a2.MC00352','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Nr5a2/FemalePN_Nr5a2.MC00352_kmeans.r')
	write_r_female('Obox1','Obox1.M01450','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox1/FemalePN_Obox1.M01450_kmeans.r')
	write_r_female('Obox2','Obox2.M01364','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox2/FemalePN_Obox2.M01364_kmeans.r')
	write_r_female('Obox3','Obox3.M01466','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox3/FemalePN_Obox3.M01466_kmeans.r')
	write_r_female('Obox5','Obox5.M01480','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Obox5/FemalePN_Obox5.M01480_kmeans.r')
	write_r_female('Osr2','Osr2.UP00052','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Osr2/FemalePN_Osr2.UP00052_kmeans.r')
	write_r_female('Otx1','Otx1.MS00586','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Otx1/FemalePN_Otx1.MS00586_kmeans.r')
	write_r_female('Otx1','Otx1.MS00587','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Otx1/FemalePN_Otx1.MS00587_kmeans.r')
	write_r_female('Pdx1','Pdx1.MC00165','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pdx1/FemalePN_Pdx1.MC00165_kmeans.r')
	write_r_female('Pknox2','Pknox2.MS00093','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pknox2/FemalePN_Pknox2.MS00093_kmeans.r')
	write_r_female('Pou2f2','Pou2f2.MS00158','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pou2f2/FemalePN_Pou2f2.MS00158_kmeans.r')
	write_r_female('Pou2f2','Pou2f2.MS00159','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pou2f2/FemalePN_Pou2f2.MS00159_kmeans.r')
	write_r_female('Pou5f1','Pou5f1.MC00233','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pou5f1/FemalePN_Pou5f1.MC00233_kmeans.r')
	write_r_female('Ppara','Ppara.MC00134','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Ppara/FemalePN_Ppara.MC00134_kmeans.r')
	write_r_female('Pparg','Pparg.MC00130','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Pparg/FemalePN_Pparg.MC00130_kmeans.r')
	write_r_female('Rara','Rara.MC00252','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/FemalePN_Rara.MC00252_kmeans.r')
	write_r_female('Rara','Rara.MS00696','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/FemalePN_Rara.MS00696_kmeans.r')
	write_r_female('Rara','Rara.MS00697','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/FemalePN_Rara.MS00697_kmeans.r')
	write_r_female('Rara','Rara.MS00698','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rara/FemalePN_Rara.MS00698_kmeans.r')
	write_r_female('Rarb','Rarb.MS00699','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rarb/FemalePN_Rarb.MS00699_kmeans.r')
	write_r_female('Rarb','Rarb.MS00700','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rarb/FemalePN_Rarb.MS00700_kmeans.r')
	write_r_female('Rarb','Rarb.MS00702','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rarb/FemalePN_Rarb.MS00702_kmeans.r')
	write_r_female('Rbfox2','Rbfox2.MC00416','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rbfox2/FemalePN_Rbfox2.MC00416_kmeans.r')
	write_r_female('Rela','Rela.MC00135','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rela/FemalePN_Rela.MC00135_kmeans.r')
	write_r_female('Rest','Rest.MC00125','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rest/FemalePN_Rest.MC00125_kmeans.r')
	write_r_female('Rfx1','Rfx1.MC00144','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rfx1/FemalePN_Rfx1.MC00144_kmeans.r')
	write_r_female('Rfx2','Rfx2.MS00170','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rfx2/FemalePN_Rfx2.MS00170_kmeans.r')
	write_r_female('Rfx2','Rfx2.MS00171','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rfx2/FemalePN_Rfx2.MS00171_kmeans.r')
	write_r_female('Rxra','Rxra.MC00471','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rxra/FemalePN_Rxra.MC00471_kmeans.r')
	write_r_female('Rxra','Rxra.MS00706','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rxra/FemalePN_Rxra.MS00706_kmeans.r')
	write_r_female('Rxra','Rxra.MS00707','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Rxra/FemalePN_Rxra.MS00707_kmeans.r')
	write_r_female('Shox2','Shox2.MS00615','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Shox2/FemalePN_Shox2.MS00615_kmeans.r')
	write_r_female('Smad2','Smad2.MC00146','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Smad2/FemalePN_Smad2.MC00146_kmeans.r')
	write_r_female('Snai1','Snai1.MC00183','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Snai1/FemalePN_Snai1.MC00183_kmeans.r')
	write_r_female('Sox15','Sox15.UP00075','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox15/FemalePN_Sox15.UP00075_kmeans.r')
	write_r_female('Sox2','Sox2.MC00303','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox2/FemalePN_Sox2.MC00303_kmeans.r')
	write_r_female('Sox6','Sox6.MC00305','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox6/FemalePN_Sox6.MC00305_kmeans.r')
	write_r_female('Sox8','Sox8.UP00051','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Sox8/FemalePN_Sox8.UP00051_kmeans.r')
	write_r_female('Srebf1','Srebf1.MS00282','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Srebf1/FemalePN_Srebf1.MS00282_kmeans.r')
	write_r_female('Srf','Srf.MC00329','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Srf/FemalePN_Srf.MC00329_kmeans.r')
	write_r_female('Stat3','Stat3.MC00140','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Stat3/FemalePN_Stat3.MC00140_kmeans.r')
	write_r_female('Stat5a','Stat5a.MC00205','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Stat5a/FemalePN_Stat5a.MC00205_kmeans.r')
	write_r_female('Tbx3','Tbx3.MC00221','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tbx3/FemalePN_Tbx3.MC00221_kmeans.r')
	write_r_female('Tcf3','Tcf3.MC00265','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tcf3/FemalePN_Tcf3.MC00265_kmeans.r')
	write_r_female('Tcf7','Tcf7.MS00054','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tcf7/FemalePN_Tcf7.MS00054_kmeans.r')
	write_r_female('Tfap2b','Tfap2b.UP00010','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfap2b/FemalePN_Tfap2b.UP00010_kmeans.r')
	write_r_female('Tfap2c','Tfap2c.UP00087','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfap2c/FemalePN_Tfap2c.UP00087_kmeans.r')
	write_r_female('Tfap2e','Tfap2e.UP00028','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfap2e/FemalePN_Tfap2e.UP00028_kmeans.r')
	write_r_female('Tfcp2l1','Tfcp2l1.MA0145','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Tfcp2l1/FemalePN_Tfcp2l1.MA0145_kmeans.r')
	write_r_female('Trp53','Trp53.MS00717','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/FemalePN_Trp53.MS00717_kmeans.r')
	write_r_female('Trp53','Trp53.MS00718','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/FemalePN_Trp53.MS00718_kmeans.r')
	write_r_female('Trp53','Trp53.MS00719','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/FemalePN_Trp53.MS00719_kmeans.r')
	write_r_female('Trp73','Trp73.MS00720','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp73/FemalePN_Trp73.MS00720_kmeans.r')
	write_r_female('Trp53','Trp53.M01655','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/FemalePN_Trp53.M01655_kmeans.r')
	write_r_female('Trp53','Trp53.MC00377','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp53/FemalePN_Trp53.MC00377_kmeans.r')
	write_r_female('Trp63','Trp63.M01656','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Trp63/FemalePN_Trp63.M01656_kmeans.r')
	write_r_female('Usf2','Usf2.MC00169','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Usf2/FemalePN_Usf2.MC00169_kmeans.r')
	write_r_female('Yy2','Yy2.M01694','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Yy2/FemalePN_Yy2.M01694_kmeans.r')
	write_r_female('Zbtb14','Zbtb14.UP00065','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zbtb14/FemalePN_Zbtb14.UP00065_kmeans.r')
	write_r_female('Zfp281','Zfp281.UP00021','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp281/FemalePN_Zfp281.UP00021_kmeans.r')
	write_r_female('Zfp410','Zfp410.UP00033','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp410/FemalePN_Zfp410.UP00033_kmeans.r')
	write_r_female('Zfp423','Zfp423.MA0116','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp423/FemalePN_Zfp423.MA0116_kmeans.r')
	write_r_female('Zfp652','Zfp652.MS00501','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp652/FemalePN_Zfp652.MS00501_kmeans.r')
	write_r_female('Zfp691','Zfp691.UP00095','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zfp691/FemalePN_Zfp691.UP00095_kmeans.r')
	write_r_female('Zscan10','Zscan10.M01742','/mnt/Storage/home/wangchenfei/MPronucleusNucleosome/Fig2.MechanismAnalysis/motifAnalysis/motif/motif/Zscan10/FemalePN_Zscan10.M01742_kmeans.r')
